---
title: "google_location"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(jsonlite)
library(tidyverse)
library(leaflet)
library(htmlwidgets)
library(ggplot2)
```

```{r}
data1=read_json(path="C:/Users/Ben/OneDrive/Documents/R/google_location/location_history.json",simplifyVector=TRUE)
data1<-data1$locations
data<-data1 %>% mutate(lat=latitudeE7/1e7) %>% mutate(lon=longitudeE7/1e7) %>% select(lat, lon) 
```

```{r,fig.width=14,fig.height=11}
samp<-sample(1e5)
subdata<-data[samp,]
subdata<-data
```

```{r}

noClusters<-150
ss<-c()

for (k in 1:noClusters){
  clus <- kmeans(as.matrix(subdata),k, iter.max=30)
  ss<-append(ss,clus$tot.withinss)
}

#map<-leaflet() %>% addTiles() %>% addCircleMarkers(subdata$lon,subdata$lat,radius=1,color='k')

map_centers<- leaflet() %>% addTiles() %>% addCircleMarkers(clus$centers[,2],clus$centers[,1], radius=2,color='b')

saveWidget(map_centers, file="test.html")

qplot(1:10, ss[1:10])

map_centers

```
```{r}

```


